config/routes.rb
QuizApp::Application.routes.draw do
  get "questions/new"
  get "users/new"

  
  root 'quizzes#index'
  resources :quizzes do 
    resources :attempts, only: [:new, :create, :show]
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/sign_out', to: 'sessions#destroy', via: 'delete'

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
    has_many :questions

    validates_presence_of :title
    accepts_nested_attributes_for :questions

    def score questions_hash
      total_correct = 0
      total = questions_hash.map do |question_id, attempt|
        question = Question.find question_id.to_i
        total_correct += 1 if attempt == question.answer
      end
      "#{ (total_correct / total.count.to_f * 100).to_i }%"
    end

end

app/models/single_attempt.rb
class SingleAttempt < ActiveRecord::Base
  
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  # attr_reader :password
  # users.password_hash in the database is a :string
  include BCrypt

  validates_presence_of :name, message: "you must fill in your name"
  validates_presence_of :email, message: "you must fill in your email"
  validates_presence_of :password, message: "you must fill in your password"
  validates_confirmation_of :password, message: "password doesn't match password confirmation"

  def password= new_password
    @password = Password.create new_password
    self.password_hash = @password
  end

  def password
    @password ||= Password.new password_hash
  end

  def self.authenticate email, password
    user = find_by_email email
    if !user.nil? && user.password == password
      user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  def new
    @quiz = Quiz.find params[:quiz_id]
  end

  def create
    @quiz = Quiz.find params[:quiz_id]
    @questions = params[:questions]
    @score = @quiz.score @questions
    flash[:notice] = "#{@score}"
    redirect_to '/'
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(params[:question].permit(:query, :option1, :option2, :option3, :option4, :answer))
    if @question.save
      flash[:notice] = "Your question was created"
      redirect_to '/'
    else
      flash[:errors] = @question.errors.values
      redirect_to '/questions/new'
    end
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  helper QuizzesHelper

  def index
    @quizzes = Quiz.all
  end

  def new
    @quiz = Quiz.new
    4.times { @quiz.questions.build }
  end

  def create
    @quiz = Quiz.create(params[:quiz].permit(:id, :title, 
      questions_attributes: [:id, :query, :option1, :option2, :option3, 
                             :option4, :answer]))

    if @quiz.save
      flash[:notice] = "Your quiz was saved"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if current_user
      @quiz = Quiz.find(params[:id])
    else
      flash[:notice] = "You must be signed in to play"
      redirect_to new_session_path
    end
  end
  
  private

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = User.new
  end

  def create
    @user = User.authenticate(params[:sessions][:email], params[:sessions][:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.name}! Please choose a quiz to play."
      redirect_to '/quizzes'
    else
      flash[:errors] = ["Your email or your password did not match. Please try again"]
      redirect_to '/sessions/new'
    end
  end

  def destroy
    flash[:notice] = "Goodbye!"
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def update

  end

  def create
    @user = User.create(params[:user].permit(:name, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You are now signed up #{@user.name}! Play a quiz!"
      redirect_to '/'
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to '/users/new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||=User.get(session[:user_id]) if session[:user_id]
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def current_user
    @current_user ||=User.get(session[:user_id]) if session[:user_id]
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def current_user
    @current_user ||=User.get(session[:user_id]) if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||=User.get(session[:user_id]) if session[:user_id]
  end
end

app/views/attempts/new.html.haml
= form_tag quiz_attempts_path do 
  - @quiz.questions.each do |question|
    %h4= question.query
    %label{for: 'option1'}
      =question.option1
      =radio_button "questions", "#{question.id}", "#{question.option1}"
    %label{for: 'option2'}
      =question.option2
      =radio_button "questions", "#{question.id}", "#{question.option2}"
    %label{for: 'option3'}
      =question.option3
      =radio_button "questions", "#{question.id}", "#{question.option3}"
    %label{for: 'option4'}
      =question.option4
      =radio_button "questions", "#{question.id}", "#{question.option4} "
  = submit_tag 'Submit'

app/views/layouts/application.html.haml
!!!
%html 
  %head 
    %title QuizApp
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav
      %a{:href => root_path}
        %h1 Welcome to QuizApp!!
      = link_to "Sign In", new_session_path
      = link_to "Sign Up", new_user_path
      = link_to "Sign Out", sign_out_path, method:'delete'
    - if flash[:errors]
      %p Sorry, there were the following problems with the form:
      %ul#errors
        - flash[:errors].each do |error|
          %li= error
    - if flash[:notice]
      #notice= flash[:notice]
    = yield

app/views/quizzes/_question_field.html.haml
= f.fields_for :f do |question_f|
  .new_questions 
    - n += 1
    = question_f.label :query, "Question #{n}"
    = question_f.text_field :query, placeholder: 'Your question here'
    = question_f.label :option1, 'Option 1'
    = question_f.text_field :option1
    = question_f.label :option2, 'Option 2'
    = question_f.text_field :option2
    = question_f.label :option3, 'Option 3'
    = question_f.text_field :option3
    = question_f.label :option4, 'Option 4'
    = question_f.text_field :option4
    = question_f.label :answer
    = question_f.text_field :answer

app/views/quizzes/index.html.haml
- @quizzes.each do |quiz|
  %ul#quiz-list 
    %li.quiz-item 
      = link_to quiz.title, quiz_path(quiz)

=  link_to "Create New Quiz", new_quiz_path(@quiz)

app/views/quizzes/new.html.haml
#new_quiz_form 
  = form_for @quiz do |f|
    - n = 0
    = f.label :title
    = f.text_field :title
    = render 'question_field', {f: f, n: n}
    = f.submit 'Create Quiz'

app/views/quizzes/show.html.haml
= @quiz.title

%ul 
  - @quiz.questions.each do |question|
    %li 
      = question.query
    %li 
      = question.option1
    %li 
      = question.option2
    %li 
      = question.option3
    %li 
      = question.option4

= button_to 'Play Quiz', new_quiz_attempt_path(@quiz), method: :get

app/views/users/new.html.haml
= form_for @user do |f|
  #name-field
    = f.label :name
    = f.text_field :name
  #email-field
    = f.label :email
    = f.text_field :email
  #password-field
    = f.label :password
    = f.text_field :password, value: ''
  #password-confirmation
    = f.label :password_confirmation
    = f.text_field :password_confirmation
  = f.submit 'Sign Up'